services:

  init:
    container_name: angel.0.init
    image: busybox

    # Note: almquist (ash) shell syntax is used here!
    entrypoint: /bin/sh -c
    command: |
              '''
              # Change the volume owner and permissions
              chown -R ${DOCKER_UID:-0}:${DOCKER_GID:-0} /volumes
              chmod -R u=rwX,g=rwX /volumes
              # Postgres database
              chown -R 70:${DOCKER_GID:-0} /volumes/local-persist/postgresql
              '''
    volumes:
      - ./local-persist/postgresql:/volumes/local-persist/postgresql
    restart: "no"

  nodejs:
    container_name: angel.server
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      # Application parameters
      - START_SCRIPT=${START_SCRIPT:-start}
      - SWAGGER_ENABLED=true
      - DEBUG_LEVEL=debug
      # Postgress database
      - DB_TYPE=postgres
      - DB_HOST=angel.postgres
      - DB_PORT=5432
      - DB_NAME=database
      - DB_USERNAME=user
      - DB_PASSWORD=password
    volumes:
      - ./src:/app/src
      - ./test:/app/test
    # Sync node_modules with the host:
    # sudo docker cp angel.server:/app/node_modules ./node_modules

    ports:
      - "3000:3000"
    healthcheck:
      # Check port 3000/TCP is open
      test: "grep -Eq \"$$(printf '[0-9]+: *[0-9A-F]{8}:%X' 3000)\" /proc/net/tcp ||
             grep -Eq \"$$(printf '[0-9]+: *[0-9A-F]{32}:%.4X' 3000)\" /proc/net/tcp6"
      interval: 2s
      retries: 30
    depends_on:
      init:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    restart: "no"

  postgres:
    image: postgres:16.2-alpine
    container_name: angel.postgres

    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./local-persist/postgresql:/var/lib/postgresql
      - ./local-persist/postgresql/data:/var/lib/postgresql/data
    healthcheck:
      # Check port 5432/TCP is open
      test: "grep -Eq \"$$(printf '[0-9]+: *[0-9A-F]{8}:%X' 5432)\" /proc/net/tcp"
      interval: 2s
      retries: 30
    depends_on:
      init:
        condition: service_completed_successfully

  adminer:
    image: wodby/adminer:4.8
    container_name: angel.adminer

    environment:
      - ADMINER_DEFAULT_DB_DRIVER=pgsql
      - ADMINER_DEFAULT_DB_HOST=angel.postgres
      - ADMINER_DEFAULT_DB_NAME=database
    ports:
      - 9000:9000
    depends_on:
      init:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    restart: "no"

networks:
  default:
    external: false
    name: docker-internal